export const VAULT_JWTROLE_IDENTIFIER = 'VAULT_JWTROLE_IDENTIFIER';
export const VAULT_ENDPOINT = 'VAULT_ENDPOINT';
export const VAULT_CA = 'VAULT_CA';
export const SFW_AUTH_ENDPOINT = 'SFW_AUTH_ENDPOINT';
export const SFW_AUTH_TENANT = 'SFW_AUTH_TENANT';
export const SFW_AUTH_CLIENT = 'SFW_AUTH_CLIENT';
export const SFW_AUTH_SECRET = 'SFW_AUTH_SECRET';
export const SFW_AUTH_VALIDITY = 'SFW_AUTH_VALIDITY';