export const VAULT_JWTROLE_IDENTIFIER = 'VAULT_JWTROLE_IDENTIFIER';
export const VAULT_ENDPOINT = 'VAULT_ENDPOINT';
export const VAULT_CA = 'VAULT_CA';
export const AUTH_ENDPOINT = 'AUTH_ENDPOINT';
export const AUTH_TENANT = 'AUTH_TENANT';
export const AUTH_CLIENT = 'AUTH_CLIENT';
export const AUTH_SECRET = 'AUTH_SECRET';
export const AUTH_VALIDITY = 'AUTH_VALIDITY';